AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./search-photos.py 
      Description: 'search photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-east-1:108752854648:function:search-photos'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos.py
      Description: 'index photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-east-1:108752854648:function:index-photos'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1